[lint]
extend-select = ["I", "NPY201"]

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"pyrecombatseq/__init__.py" = ["I"]
"pyrecombatseq/edgepy/__init__.py" = ["I"]

[format]
exclude = ["pyrecombatseq/__init__.py"]
